### PR TITLE
Invoking callback early on error to avoid further, misleading errors

### PR DESCRIPTION
**Pull request by ihenshaw**
When attempting to use an indexPath where the directory didn't exist, I was presented with an error that was misleading..

TypeError: Cannot read property 'add' of null

This PR resolves the issue by aborting the attempt to create an index if an error has already occurred.

### CODE REVIEW

**Comment by fergiemcdowall** [comment]
Hmmm- its crashing selenium for some reason

You can see if your changes work by doing `npm test` before deploying (or just `npm run test-browserify` to test the web stuff that seems to be breaking)

**Comment by ihenshaw** [comment]
I know the changes are safe, because i'm using them, there's not much
really to go around.

I just ran npm test here and it runs just great!

Here is the output from test-browserify...

enshawi@localhost:~/git/github.com/ihenshaw/search-index$ npm run
test-browserify

> search-index@0.8.8 test-browserify /Users/henshawi/git/
github.com/ihenshaw/search-index
> browserify test/browser/browserify-test-uncompiled.js | uglifyjs >
test/sandbox/bundle.js && tape test/browser/selenium-test.js

(node) util.print is deprecated. Use console.log instead.
TAP version 13
# check size of bundle
855370
ok 1 bundle should be less than 1mb
# start server
ok 2 undefined
# connect to test html page
ok 3 should be equal
ok 4 should be equal
# teardown

1..4
# tests 4
# pass  4

# ok

Something with Travis maybe?

I'll take a look later if I get a chance, need to head home now. Thanks for
looking.

Cheers
Ian

**Comment by fergiemcdowall** [comment]
Ah- quite possibly something with Travis then. I'll take a look at it as well

**Comment by ihenshaw** [comment]
Did you have any joy with figuring out what was wrong with Travis or are you discarding this patch?

Cheers
Ian

**Comment by fergiemcdowall** [comment]
Still failing- dont really have time to look at this just now, but we can leave it here for the time being

**Pull request closed without merging**
