### PR TITLE
Upstream pr

### PR DESCRIPTION
**Pull request by kldavis4**
- updates search-index to use new version of fii that is initialized with db instance instead of class (https://github.com/fergiemcdowall/fergies-inverted-index/pull/58)
- makes memory-level the default database to avoid binary deps from classic-level

### CODE REVIEW

**Comment by kldavis4** [comment]
@fergiemcdowall this is currently built against our forked version - will need to be updated once you publish the fii update

**Comment by fergiemcdowall** [comment]
@kldavis4 @jeffsee55 Just realized that I incremented too much- the correct new version is 4 not 5. Therefore 5.0.0-rc1 is deprectated- use search-index@4.0.0-rc1 instead.

**Comment by kldavis4** [comment]
> @kldavis4 @jeffsee55 Just realized that I incremented too much- the correct new version is 4 not 5. Therefore 5.0.0-rc1 is deprecated- use search-index@4.0.0-rc1 instead.

ok, makes sense - thanks @fergiemcdowall

**Comment by fergiemcdowall** [comment]
OK- great- in that case I will merge in the changes

**Comment by fergiemcdowall** [comment]
@kldavis4 changes merged into `search-index@12`

**Pull request merged**
