### PR TITLE
check if filters is array

### LINKED ISSUE #83: si.add is broken
When trying to run the following code
```javascript
var batch = [
  {
    'id':'1',
    'title':'A really interesting document',
    'body':'This is a really interesting document',
    'metadata':['red', 'potato']
  }
];

si.add({batchName: 'firstBatch'}, batch, function (err) {
  if (err) console.log(err)
});

```
I get the following error.

```
/Users/mats/Documents/dev/norch/node_modules/search-index/lib/indexing/indexer.js:57
  for (var i = 0; i < facets.length; i++) {
                            ^
TypeError: Cannot read property 'length' of undefined
```

Git blame points to @fergiemcdowall's commit 2 days ago ;)

### PR DESCRIPTION
**Pull request by mewwts**
fixes #83, but perhaps not the underlying issue?

### CODE REVIEW

**Comment by mewwts** [comment]
Will take a look and check why the build fails. :+1:

**Comment by mewwts** [comment]
This runs perfectly on my machine.

**Comment by fergiemcdowall** [comment]
Ahh- I changed the syntax of filters and facets, but havent updated to docs yet. Maybe thats why? The tests have the right syntax

**Comment by mewwts** [comment]
Hmm, unsure. But I feel that this PR is a hack. Some underlying cause perhaps need to be fixed instead?

**Comment by fergiemcdowall** [comment]
Its actually 9.6instantiation-spec.js that is breaking on travis...

**Pull request closed without merging**
