### PR TITLE
Add iojs for tests at travis.

### PR DESCRIPTION
**Pull request by mewwts**

### CODE REVIEW

**Comment by mewwts** [comment]
Lul, I absolutely can't see the failing test case in the logs!

**Comment by fergiemcdowall** [comment]
Bad things happening- not sure why...

F

On Sat, Aug 15, 2015 at 7:39 PM, Mats Julian Olsen <notifications@github.com

**Comment by mewwts** [comment]
Yup. Looks like the npm install fails on the iojs side. Probably something silly.

**Comment by mewwts** [comment]
Ah, OK.
See https://github.com/nodejs/node/issues/433

**Comment by mewwts** [comment]
Btw @fergiemcdowall looks like the configuration test fails off and on. Fixes itself when I rerun it. Any clues?

**Comment by mewwts** [comment]
Will just leave this here unmerged while I research this.

**Comment by mewwts** [comment]
I rebased onto master.

**Comment by mewwts** [comment]
This faiils on the node.js side:
```
1) Matching epub:  should match on all fields and return IDs:

      AssertionError: expected false to be true

      + expected - actual

      -false

      +true

      

      at test/general-tests/matching-test.js:79:32

      at Object.matcher.matcher (lib/matchers/matcher.js:12:14)

      at Object.SearchIndex.match (lib/search-index.js:194:13)

      at Context.<anonymous> (test/general-tests/matching-test.js:77:8)


```
It fails on my computer too, @fergiemcdowall?

**Comment by mewwts** [comment]
Trying this again.

**Pull request closed without merging**
