### PR TITLE
Remove match string length validation. Clients should do their own va…

### PR DESCRIPTION
**Pull request by lannka**
…lidation, instead of replying on search-index to do so.

### CODE REVIEW

**Comment by lannka** [comment]
Fixed the failed test case by removing it :-). As I think it's already covered by the test case in general-tests. Let me know if it was intentional to duplicate.

**Comment by fergiemcdowall** [comment]
The tests are failing because of some weirdness in Travis. Its a shame that this has come at a time when the project is getting a lot of pull requests. I am going to try and fix the tests

**Comment by fergiemcdowall** [comment]
Oh- yes, I see what you mean now. I am going to rewrite the matcher interface so that it takes an options object, where `threshold` is one of the options

**Comment by lannka** [comment]
It would be great to have an options for the matcher. But I think we don't need a "threshold" option there. In my opinion, such kind of "threshold validation" can always be done in caller, I don't see benefit to do it inside search-index.

**Comment by fergiemcdowall** [comment]
Thats certainly a valid point.

**Comment by lannka** [comment]
Hi @fergiemcdowall , how can we make this change available in "npm install search-index"? Do we need to bump the version to 0.6.4?

**Comment by fergiemcdowall** [comment]
I am hopefully going to publish later today (CET)

**Comment by fergiemcdowall** [comment]
This is now published to npm.

I changed the API slightly, so that `matcher` takes an `options` object. [details here](https://github.com/fergiemcdowall/search-index/blob/master/doc/autosuggest.md). For your use-case you need to set `threshold: 1` I think...

**Pull request merged**
