### PR TITLE
Enhanced logging and module instantiation

### PR DESCRIPTION
**Pull request by mewwts**
Most modules now exports a function that accepts a options object;
``` module.exports = function (options) {} ```
This allows for sharing child loggers from bunyan.
Modules other than search-index.js also uses `bunyan-shadower` so that we don't have to require a logger or alter the logging code.

### CODE REVIEW

**Comment by mewwts** [comment]
I don't know how to include your changes in this @fergiemcdowall.

**Comment by fergiemcdowall** [comment]
phew! * mops brow *

**Comment by fergiemcdowall** [comment]
I really like the new structure, especially the way that you can pass options

**Comment by mewwts** [comment]
I'm in awe of your merging skills!

**Pull request merged**
