### PR TITLE
Code style refactoring

### PR DESCRIPTION
**Pull request by MrRefactoring**
* Slightly improved the code style.
* Eliminated the vulnerabilities that remained in the `standard` package
* Removed dead code

### CODE REVIEW

**Comment by fergiemcdowall** [comment]
I really appreciate the time that you have put into this, so I feel a bit bad about not accepting it straight away. Code style is something that contributors feel strongly about so a consensus should be reached before making changes.

The big win with ´standard´ is that we don't have to use energy on [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding).

That said I was curious about this line: "Eliminated the vulnerabilities that remained in the ´standard´ package". What vulnerabilities?

**Comment by MrRefactoring** [comment]
Yes, I agree that the changes are quite controversial.

I'll start with the vulnerabilities. This is what the `npm audit` gives us:

```bash
~ npm audit

                       === npm audit security report ===

# Run  npm update js-yaml --depth 3  to resolve 2 vulnerabilities

  Moderate        Denial of Service

  Package         js-yaml

  Dependency of   standard [dev]

  Path            standard > eslint > js-yaml

  More info       https://npmjs.com/advisories/788




  High            Code Injection

  Package         js-yaml

  Dependency of   standard [dev]

  Path            standard > eslint > js-yaml

  More info       https://npmjs.com/advisories/813



found 2 vulnerabilities (1 moderate, 1 high) in 10047 scanned packages
  run `npm audit fix` to fix 2 of them.
```

As for the code. I noticed that there are misprints, pieces of code and dependencies that are not involved in the work. The var is also somewhere used, and the let and const somewhere are used.

More fine-tuning eslint avoids some of the problems. But I do not insist, since this is a rather subtle question that is left to your discretion.

**Comment by MrRefactoring** [comment]
As an option, we can refuse eslint, but leave improvements

**Comment by fergiemcdowall** [comment]
Yes, if you could remove 

1. changes to package.json
2. The extra config files
3. whitespace changes

Then I would be happy to merge the other changes

**Comment by fergiemcdowall** [comment]
Regarding the output of ´npm audit´: wouldn't that same security hole be there with plain old ´eslint´?

**Comment by MrRefactoring** [comment]
eslint is updated more often and closes security holes than standard.

.editorconfig should also be removed?

**Comment by fergiemcdowall** [comment]
Right, but ´standard´ is just a wrapper round ´eslint´, so the security fix should make its way downstream soon? (I will keep an eye on this). Given that this is a `devDependency` it should be safe enough to tolerate the risk of DOS and code injection for a short period of time.

Yes, .editorconfig should be removed

**Comment by MrRefactoring** [comment]
Yes you are right. Hopefully this will be fixed soon. (True updates have not been out for 9 months already)

**Comment by fergiemcdowall** [comment]
:+1:

**Pull request merged**
